from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
import uuid
from pathlib import Path

import requests


def default_openvino_device() -> str:
    try:
        import openvino as ov

        devices = ov.Core().available_devices
        if "GPU" in devices:
            return "GPU"
    except Exception:
        pass
    return "CPU"


def find_comfyui_dir(explicit_dir: str | None = None) -> Path:
    if explicit_dir:
        comfyui_dir = Path(explicit_dir).expanduser().resolve()
        if (comfyui_dir / "main.py").exists():
            return comfyui_dir
        raise FileNotFoundError(f"Could not find ComfyUI main.py in: {comfyui_dir}")

    current = Path(__file__).resolve()
    for parent in current.parents:
        if (parent / "main.py").exists() and (parent / "custom_nodes").exists():
            return parent
        nested = parent / "ComfyUI"
        if (nested / "main.py").exists():
            return nested
    raise FileNotFoundError("Could not locate ComfyUI. Pass --comfyui-dir explicitly.")


def wait_for_server(base_url: str, timeout_s: int = 120) -> None:
    deadline = time.time() + timeout_s
    last_error = None
    while time.time() < deadline:
        try:
            response = requests.get(f"{base_url}/system_stats", timeout=5)
            if response.status_code == 200:
                return
            last_error = RuntimeError(f"HTTP {response.status_code}: {response.text[:200]}")
        except Exception as exc:
            last_error = exc
        time.sleep(2)
    raise RuntimeError(f"ComfyUI did not become ready within {timeout_s}s: {last_error}")


def queue_prompt(base_url: str, prompt: dict) -> str:
    payload = {
        "client_id": str(uuid.uuid4()),
        "prompt": prompt,
    }
    response = requests.post(f"{base_url}/prompt", json=payload, timeout=30)
    response.raise_for_status()
    data = response.json()
    return data["prompt_id"]


def wait_for_prompt(base_url: str, prompt_id: str, timeout_s: int = 600) -> dict:
    deadline = time.time() + timeout_s
    last_error = None
    while time.time() < deadline:
        try:
            response = requests.get(f"{base_url}/history/{prompt_id}", timeout=30)
            response.raise_for_status()
            history = response.json()
            if prompt_id in history:
                return history[prompt_id]
        except Exception as exc:
            last_error = exc
        time.sleep(3)
    raise RuntimeError(f"Prompt {prompt_id} did not finish within {timeout_s}s: {last_error}")


def build_argparser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Verify ComfyUI can run ERNIE-Image through the local OpenVINO node.")
    parser.add_argument(
        "--prompt",
        default="a centered whole red apple on a wooden table, studio lighting, sharp focus, high quality",
        help="Text prompt for generation.",
    )
    parser.add_argument("--negative-prompt", default="", help="Negative prompt.")
    parser.add_argument("--width", type=int, default=512, help="Output width.")
    parser.add_argument("--height", type=int, default=512, help="Output height.")
    parser.add_argument("--steps", type=int, default=8, help="Number of denoising steps.")
    parser.add_argument("--guidance-scale", type=float, default=1.0, help="Classifier-free guidance scale.")
    parser.add_argument("--seed", type=int, default=123, help="Random seed.")
    parser.add_argument("--device", help="Default OpenVINO device. Defaults to GPU when available, otherwise CPU.")
    parser.add_argument("--load-pe", action=argparse.BooleanOptionalAction, default=True, help="Load Prompt Enhancer when available.")
    parser.add_argument("--use-pe", action=argparse.BooleanOptionalAction, default=True, help="Use Prompt Enhancer during generation.")
    parser.add_argument("--pe-max-new-tokens", type=int, default=256, help="Maximum new tokens generated by PE.")
    parser.add_argument("--text-encoder-device", default="", help="Optional device override for text encoder.")
    parser.add_argument("--transformer-device", default="", help="Optional device override for transformer.")
    parser.add_argument("--vae-decoder-device", default="", help="Optional device override for VAE decoder.")
    parser.add_argument("--port", type=int, default=8190, help="Temporary ComfyUI server port.")
    parser.add_argument("--timeout", type=int, default=1200, help="Maximum seconds to wait for the prompt to finish.")
    parser.add_argument("--filename-prefix", default="ov_ernie_comfy_api", help="SaveImage filename prefix.")
    parser.add_argument("--model-dir", help="OpenVINO ERNIE-Image model directory.")
    parser.add_argument("--comfyui-dir", help="Path to the ComfyUI directory. Auto-detected by default.")
    parser.add_argument(
        "--custom-node-name",
        help="Custom node folder name for ComfyUI's --whitelist-custom-nodes option. Defaults to this repo folder.",
    )
    return parser


def main() -> int:
    args = build_argparser().parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    comfy_dir = find_comfyui_dir(args.comfyui_dir)
    python_exe = Path(sys.executable)
    log_dir = repo_root / ".logs"
    log_dir.mkdir(exist_ok=True)
    stdout_log = log_dir / "verify_comfyui_server_stdout.log"
    stderr_log = log_dir / "verify_comfyui_server_stderr.log"
    port = args.port
    base_url = f"http://127.0.0.1:{port}"
    device = args.device or default_openvino_device()
    model_dir = Path(args.model_dir).expanduser().resolve() if args.model_dir else repo_root / "ERNIE-Image-Turbo-ov-int4"
    custom_node_name = args.custom_node_name or repo_root.name

    command = [
        str(python_exe),
        "main.py",
        "--listen",
        "127.0.0.1",
        "--port",
        str(port),
        "--disable-auto-launch",
        # Intel AI PCs do not need CUDA for this workflow. ComfyUI still needs
        # this flag so its PyTorch device discovery does not initialize CUDA.
        "--cpu",
        "--log-stdout",
        "--database-url",
        "sqlite:///:memory:",
        "--whitelist-custom-nodes",
        custom_node_name,
    ]

    with stdout_log.open("w", encoding="utf-8", errors="replace") as stdout, stderr_log.open(
        "w", encoding="utf-8", errors="replace"
    ) as stderr:
        process = subprocess.Popen(
            command,
            cwd=comfy_dir,
            stdout=stdout,
            stderr=stderr,
            text=True,
        )

        try:
            wait_for_server(base_url)
            prompt = {
                "1": {
                    "class_type": "OVErnieImageTextToImage",
                    "inputs": {
                        "model_dir": str(model_dir),
                        "prompt": args.prompt,
                        "negative_prompt": args.negative_prompt,
                        "device": device,
                        "load_pe": args.load_pe,
                        "use_pe": args.use_pe,
                        "pe_max_new_tokens": args.pe_max_new_tokens,
                        "text_encoder_device": args.text_encoder_device,
                        "transformer_device": args.transformer_device,
                        "vae_decoder_device": args.vae_decoder_device,
                        "width": args.width,
                        "height": args.height,
                        "steps": args.steps,
                        "guidance_scale": args.guidance_scale,
                        "seed": args.seed,
                    },
                },
                "2": {
                    "class_type": "SaveImage",
                    "inputs": {
                        "filename_prefix": args.filename_prefix,
                        "images": ["1", 0],
                    },
                },
            }
            prompt_id = queue_prompt(base_url, prompt)
            history = wait_for_prompt(base_url, prompt_id, timeout_s=args.timeout)
            outputs = history.get("outputs", {})
            saved = outputs.get("2", {}).get("images", [])
            print(f"prompt_id={prompt_id}")
            print(json.dumps(saved, indent=2))
            if not saved:
                raise RuntimeError(f"No SaveImage output found. History: {json.dumps(history)[:1000]}")
            return 0
        finally:
            process.terminate()
            try:
                process.wait(timeout=20)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait(timeout=20)


if __name__ == "__main__":
    raise SystemExit(main())
